### ISSUE TITLE
at least python3.6 is required

### ISSUE THREAD

**Issue by magneticnorth** [tnakae/DAGMM#18]
Greetings. Thank you for making this software available.  The github page states that python 3 is a pre-requisite, but it turns out DAGMM uses python f-strings, which first appeared in python 3.6.  They don't work in python 3.5, which is the default in environments such as ubuntu 16.04.5 on AWS nVidia GPU nodes. If you can update the documentation, that will help.

**Comment by tnakae** [comment]
@magneticnorth 
Thank you for your comments, and I'm sorry about imperfect description about Python version.
I changed all f-strings to format functions. You can use it in Python 3.5 now.
