### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by aktaseren** [tnakae/DAGMM#22]
Thank you for making this library available. I followed the requirements below on my virtual environment:

python (3.5-3.6)
Tensorflow <= 1.15
Numpy
sklearn

I use python 3.5.6, Tensorflow 1.14.0, NumPy 1.16.4, scikit-learn 0.20.1 but I am still having requirement issue below on that virtual environment:

ERROR: Could not find a version that satisfies the requirement DAGMM
ERROR: No matching distribution found for DAGMM

Can you please clarify the requirements? That would be great.

**Comment by tnakae** [comment]
@aktaseren 

> I use python 3.5.6, Tensorflow 1.14.0, NumPy 1.16.4, scikit-learn 0.20.1 but I am still having requirement issue below on 
that virtual environment:

I think package versions in your environment are sufficient to execute dagmm.

To check package dependency, I wrote down `Dockerfile` in feature branch,
executed test code. This code was executed correctly.

feature branch : https://github.com/tnakae/DAGMM/compare/feature_docker-image

**Procedure**
1. check out feature branch
  - `git checkout feature_docker-image`
1. build image and execute test code
  - `docker-compose up --build`

**Message from test code** (omitted warnings)
```
dagmm_1  |  epoch 100/1000 : loss = 2.821                                                                                                                    
dagmm_1  |  epoch 200/1000 : loss = 2.047                                                                                                                    
dagmm_1  |  epoch 300/1000 : loss = 1.942                                                                                                                    
dagmm_1  |  epoch 400/1000 : loss = 1.889                                                                                                                    
dagmm_1  |  epoch 500/1000 : loss = 1.834                                                                                                                    
dagmm_1  |  epoch 600/1000 : loss = 1.771                                                                                                                    
dagmm_1  |  epoch 700/1000 : loss = 1.676                                                                                                                    
dagmm_1  |  epoch 800/1000 : loss = 1.474                                                                                                                    
dagmm_1  |  epoch 900/1000 : loss = 1.228                                                                                                                    
dagmm_1  |  epoch 1000/1000 : loss = 1.003                                                                                                                   
dagmm_1  | fitted_energy = -2.398                                                                                                                            
dagmm_dagmm_1 exited with code 0                                                                                                                             
```

**Comment by aktaseren** [comment]
@tnakae thank you for that quick recommendation and docker image. The docker image guided me well. Weirdly, from sklearn.externals import joblib line was making an error on these requirements. Joblib is removed from scikit-learn as its own library although I made it downgraded to scikit-learn 0.20.1. I updated that line as import joblib in dagmm.py on my local machine. It is working now.
